# Premium-minds - Billy .travis.yml

language: java

# Avoid default OracleJDK7. Complies with Eclipse environment used
jdk:
    - openjdk6
    
before_script:
	- chmod +x ./share/deploy/deploy-snapshot.sh
    
after_success:
	- ./share/deploy/deploy-snapshot.sh

notifications:
    email:
        recipients:
            - froxo@pminds.pt
        on_failure: always
