# Premium-minds - Billy .travis.yml

language: java

# Avoid default OracleJDK7. Complies with Eclipse environment used
jdk:
    - openjdk6

notifications:
    email:
        recipients:
            - estagio1@premium-minds.com
        on_failure: always
