# Premium-minds - Billy .travis.yml

language: java

jdk:
    - openjdk7
    
before_script:
    - chmod +x ./share/deploy/deploy-snapshot.sh
    
after_success:
    - ./share/deploy/deploy-snapshot.sh

notifications:
    email:
        recipients:
            - froxo@pminds.pt
        on_failure: always
